(() => {
  const canvas = document.getElementById('canvas');
  const ctx = canvas.getContext('2d');
  const assetCanvas = document.getElementById('assetCanvas');
  const assetCtx = assetCanvas.getContext('2d');
  const cropPreview = document.getElementById('cropPreview');
  const cropCtx = cropPreview.getContext('2d');

  const $ = (id) => document.getElementById(id);
  const els = {
    mapSelect: $('mapSelect'), refreshBtn: $('refreshBtn'), loadBtn: $('loadBtn'), mapId: $('mapId'), displayName: $('displayName'), width: $('width'), height: $('height'), tileSize: $('tileSize'), projectRootHint: $('projectRootHint'), visualFileHint: $('visualFileHint'),
    semanticModeBtn: $('semanticModeBtn'), assetModeBtn: $('assetModeBtn'), modeSummary: $('modeSummary'), viewMode: $('viewMode'),
    semanticPanel: $('semanticPanel'), assetPanel: $('assetPanel'), activeLayer: $('activeLayer'), brushSize: $('brushSize'), palette: $('palette'), semanticEraserBtn: $('semanticEraserBtn'), clearSemanticLayerBtn: $('clearSemanticLayerBtn'), saveSemanticBtn: $('saveSemanticBtn'),
    placeToolBtn: $('placeToolBtn'), selectToolBtn: $('selectToolBtn'), eraseToolBtn: $('eraseToolBtn'), assetFolderSelect: $('assetFolderSelect'), assetSearch: $('assetSearch'), assetSelect: $('assetSelect'), reloadAssetsBtn: $('reloadAssetsBtn'), validateVisualBtn: $('validateVisualBtn'),
    sheetZoom: $('sheetZoom'), sheetPanX: $('sheetPanX'), sheetPanY: $('sheetPanY'), cropX: $('cropX'), cropY: $('cropY'), cropW: $('cropW'), cropH: $('cropH'), gridSize: $('gridSize'), snapToGrid: $('snapToGrid'), stampLine: $('stampLine'), cropInfo: $('cropInfo'),
    drawLayer: $('drawLayer'), drawWTiles: $('drawWTiles'), drawHTiles: $('drawHTiles'), anchor: $('anchor'), drawOrder: $('drawOrder'), placementLabel: $('placementLabel'), duplicateBtn: $('duplicateBtn'), deleteBtn: $('deleteBtn'), copyBtn: $('copyBtn'), pasteBtn: $('pasteBtn'), sendBackBtn: $('sendBackBtn'), bringFrontBtn: $('bringFrontBtn'), undoBtn: $('undoBtn'), redoBtn: $('redoBtn'), saveVisualBtn: $('saveVisualBtn'), downloadVisualBtn: $('downloadVisualBtn'), selectedPlacementInfo: $('selectedPlacementInfo'),
    layerVisibility: $('layerVisibility'), visualVisibility: $('visualVisibility'), showAllBtn: $('showAllBtn'), soloBtn: $('soloBtn'), showGrid: $('showGrid'), showSemanticOverlay: $('showSemanticOverlay'), semanticOverlayAlpha: $('semanticOverlayAlpha'), showMarkerGlyphs: $('showMarkerGlyphs'),
    statusLine: $('statusLine'), fileHud: $('fileHud'), modeHud: $('modeHud'), selectedHud: $('selectedHud'), tileHud: $('tileHud'), hoverHud: $('hoverHud'), zoomHud: $('zoomHud')
  };

  const SEMANTIC_LAYERS = ['ground', 'structures', 'objects', 'markers'];
  const VISUAL_LAYERS = ['ground', 'structures', 'objects', 'foreground'];
  const LAYER_LABELS = { ground: 'Ground', structures: 'Structures', objects: 'Objects', markers: 'Markers' };
  const VISUAL_LAYER_LABELS = { ground: 'Visual Ground', structures: 'Visual Structures', objects: 'Visual Objects', foreground: 'Visual Foreground' };
  const PALETTES = {
    ground: [
      { id: 'indoor_floor', label: 'Indoor Floor', color: '#c9b99a' }, { id: 'floor', label: 'Floor', color: '#b8b0a2' }, { id: 'street', label: 'Street', color: '#3f3f46' }, { id: 'sidewalk', label: 'Sidewalk', color: '#d8dee9' }, { id: 'grass', label: 'Grass', color: '#22c55e' }, { id: 'parking_lot', label: 'Parking Lot', color: '#64748b' }, { id: 'crosswalk', label: 'Crosswalk', color: '#fef08a' }, { id: 'dirt_path', label: 'Dirt Path', color: '#a16207' }, { id: 'water', label: 'Water', color: '#0ea5e9' }
    ],
    structures: [
      { id: 'exterior_wall', label: 'Exterior Wall', color: '#2563eb' }, { id: 'interior_wall', label: 'Interior Wall', color: '#111827' }, { id: 'building_shell', label: 'Building Shell', color: '#7c3aed' }, { id: 'player_apartment_building', label: 'Player Apt Building', color: '#8b5cf6' }, { id: 'charles_jr_building', label: 'Charles Jr Building', color: '#f97316' }, { id: 'apartment_building', label: 'Apartment Building', color: '#6366f1' }, { id: 'doorway', label: 'Doorway', color: '#fb923c' }, { id: 'entrance_exit', label: 'Entrance / Exit', color: '#facc15' }, { id: 'window', label: 'Window', color: '#38bdf8' }, { id: 'collision_block', label: 'Collision Block', color: '#020617' }, { id: 'fence', label: 'Fence', color: '#78350f' }
    ],
    objects: [
      { id: 'bed', label: 'Bed', color: '#a855f7' }, { id: 'couch', label: 'Couch', color: '#ef4444' }, { id: 'table', label: 'Table', color: '#92400e' }, { id: 'dining_table', label: 'Dining Table', color: '#b45309' }, { id: 'booth_seat', label: 'Booth Seat', color: '#dc2626' }, { id: 'cashier_counter', label: 'Cashier Counter', color: '#0f766e' }, { id: 'refrigerator', label: 'Refrigerator', color: '#67e8f9' }, { id: 'stove', label: 'Stove', color: '#334155' }, { id: 'sink', label: 'Sink', color: '#94a3b8' }, { id: 'counter_top', label: 'Counter Top', color: '#14b8a6' }, { id: 'dog_bowl', label: 'Dog Bowl', color: '#fbbf24' }, { id: 'dog_bed', label: 'Dog Bed', color: '#f59e0b' }, { id: 'tree', label: 'Tree', color: '#166534' }, { id: 'bush', label: 'Bush', color: '#65a30d' }, { id: 'furniture_appliance', label: 'Furniture / Appliance', color: '#f472b6' }
    ],
    markers: [
      { id: 'player_spawn', label: 'Player Spawn', color: '#ffffff' }, { id: 'player_door', label: 'Player Door', color: '#38bdf8' }, { id: 'charles_jr_door', label: 'Charles Jr Door', color: '#fb923c' }, { id: 'transition_to_home', label: 'Transition to Home', color: '#22d3ee' }, { id: 'transition_to_charles_jr', label: 'Transition to Charles Jr', color: '#f59e0b' }, { id: 'npc_spawn', label: 'NPC Spawn', color: '#fde68a' }, { id: 'cashier_spawn', label: 'Cashier Spawn', color: '#fb7185' }, { id: 'dog_spawn', label: 'Dog Spawn', color: '#84cc16' }, { id: 'dog_interaction', label: 'Dog Interaction', color: '#bef264' }, { id: 'entrance_exit', label: 'Entrance / Exit', color: '#facc15' }, { id: 'order_interaction', label: 'Order Interaction', color: '#f97316' }, { id: 'walkable_area', label: 'Walkable Area', color: '#86efac' }, { id: 'seating_area', label: 'Seating Area', color: '#c084fc' }, { id: 'event_zone', label: 'Event Zone', color: '#ff2d55' }, { id: 'interior_door', label: 'Interior Door', color: '#06b6d4' }, { id: 'save_point', label: 'Save Point', color: '#22d3ee' }, { id: 'bed_interaction', label: 'Bed Interaction', color: '#c084fc' }, { id: 'fridge_interaction', label: 'Fridge Interaction', color: '#7dd3fc' }, { id: 'interaction_point', label: 'Interaction Point', color: '#f59e0b' }, { id: 'kitchen_zone', label: 'Kitchen Zone', color: '#2dd4bf' }, { id: 'room_zone', label: 'Room Zone', color: '#a78bfa' }
    ]
  };
  const colorById = {}; const labelById = {};
  for (const list of Object.values(PALETTES)) for (const item of list) { colorById[item.id] = item.color; labelById[item.id] = item.label; }

  const state = {
    maps: [], fileName: null, visualFileName: null, map: null, visual: null, visualSource: null,
    editMode: 'semantic', viewMode: 'semantic', activeLayer: 'ground', selectedSemantic: 'indoor_floor', semanticVisibility: { ground:true, structures:true, objects:true, markers:true },
    visualTool: 'place', visualVisibility: { ground:true, structures:true, objects:true, foreground:true }, selectedPlacementId: null, copiedPlacement: null,
    assets: [], folders: [], folderFilter: 'ALL', assetImage: null, assetImagePath: null, assetImageInfo: null, sheetPan: {x:0,y:0}, crop: {x:0,y:0,width:32,height:32},
    imageCache: new Map(), zoom: 1, panX: 0, panY: 0, pointer: { down:false, mode:null, lastX:0, lastY:0, dragStartTile:null, movedPlacementStart:null, lastPlacedKey:null },
    sheetPointer: {down:false, mode:null, lastX:0, lastY:0}, hoverTile: null, dirtySemantic: false, dirtyVisual: false, undoStack: [], redoStack: []
  };

  async function api(path, options = {}) {
    const res = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } });
    const text = await res.text();
    let data; try { data = JSON.parse(text); } catch { data = text; }
    if (!res.ok) throw new Error(data?.error || text || res.statusText);
    return data;
  }
  async function init() {
    setupUi(); setupCanvas(); setupAssetCanvas(); populateLayerSelect(); renderPalette(); renderVisibility(); renderVisualVisibility();
    await Promise.all([refreshMaps(), refreshAssets()]);
    setEditorMode('semantic', { keepView: true });
    requestAnimationFrame(draw);
  }
  function setupUi() {
    els.refreshBtn.onclick = refreshMaps; els.loadBtn.onclick = loadSelectedMap; els.mapSelect.ondblclick = loadSelectedMap;
    els.semanticModeBtn.onclick = () => setEditorMode('semantic'); els.assetModeBtn.onclick = () => setEditorMode('asset');
    els.viewMode.onchange = () => { state.viewMode = els.viewMode.value; updateHud(); };
    els.activeLayer.onchange = () => { state.activeLayer = els.activeLayer.value; if (!PALETTES[state.activeLayer].some(i => i.id === state.selectedSemantic)) state.selectedSemantic = PALETTES[state.activeLayer][0]?.id || null; renderPalette(); renderVisibility(); updateHud(); };
    els.semanticEraserBtn.onclick = () => { state.selectedSemantic = null; renderPalette(); updateHud(); setStatus('Semantic eraser selected.'); };
    els.clearSemanticLayerBtn.onclick = clearSemanticLayer; els.saveSemanticBtn.onclick = saveSemantic;
    for (const el of [els.mapId, els.displayName]) el.oninput = () => { state.dirtySemantic = true; updateHud(); };
    els.placeToolBtn.onclick = () => setVisualTool('place'); els.selectToolBtn.onclick = () => setVisualTool('select'); els.eraseToolBtn.onclick = () => setVisualTool('erase');
    els.assetFolderSelect.onchange = () => { state.folderFilter = els.assetFolderSelect.value; renderAssetOptions(); };
    els.assetSearch.oninput = renderAssetOptions; els.reloadAssetsBtn.onclick = refreshAssets; els.assetSelect.onchange = loadSelectedAsset;
    for (const el of [els.sheetZoom, els.sheetPanX, els.sheetPanY]) el.oninput = () => { state.sheetPan.x = Number(els.sheetPanX.value||0); state.sheetPan.y = Number(els.sheetPanY.value||0); drawAssetSheet(); };
    for (const el of [els.cropX, els.cropY, els.cropW, els.cropH, els.gridSize, els.snapToGrid]) el.oninput = syncCropFromInputs;
    for (const el of [els.drawLayer, els.drawWTiles, els.drawHTiles, els.anchor, els.drawOrder, els.placementLabel]) el.oninput = syncSelectedPlacementFromForm;
    els.duplicateBtn.onclick = duplicateSelected; els.deleteBtn.onclick = deleteSelected; els.copyBtn.onclick = copySelected; els.pasteBtn.onclick = pasteCopied; els.sendBackBtn.onclick = () => bumpOrder(-1); els.bringFrontBtn.onclick = () => bumpOrder(1);
    els.undoBtn.onclick = undo; els.redoBtn.onclick = redo; els.validateVisualBtn.onclick = validateVisual; els.saveVisualBtn.onclick = saveVisual; els.downloadVisualBtn.onclick = downloadVisual;
    els.showAllBtn.onclick = showAllLayers; els.soloBtn.onclick = soloActiveLayer;
    for (const el of [els.showGrid, els.showSemanticOverlay, els.semanticOverlayAlpha, els.showMarkerGlyphs]) el.oninput = updateHud;
    window.addEventListener('keydown', onKeyDown);
  }
  function setupCanvas() {
    window.addEventListener('resize', resizeCanvas); canvas.addEventListener('contextmenu', e => e.preventDefault()); canvas.addEventListener('mousedown', pointerDown); canvas.addEventListener('mousemove', pointerMove); window.addEventListener('mouseup', pointerUp); canvas.addEventListener('wheel', onWheel, {passive:false}); resizeCanvas();
  }
  function setupAssetCanvas() {
    assetCanvas.addEventListener('contextmenu', e => e.preventDefault()); assetCanvas.addEventListener('mousedown', sheetPointerDown); assetCanvas.addEventListener('mousemove', sheetPointerMove); window.addEventListener('mouseup', sheetPointerUp); assetCanvas.addEventListener('wheel', onSheetWheel, {passive:false});
  }
  function setEditorMode(mode, options={}) {
    state.editMode = mode === 'asset' ? 'asset' : 'semantic';
    if (!options.keepView) state.viewMode = state.editMode === 'asset' ? 'asset' : 'semantic';
    els.viewMode.value = state.viewMode; els.semanticPanel.hidden = state.editMode !== 'semantic'; els.assetPanel.hidden = state.editMode !== 'asset';
    els.semanticModeBtn.classList.toggle('active', state.editMode === 'semantic'); els.assetModeBtn.classList.toggle('active', state.editMode === 'asset');
    els.modeSummary.textContent = state.editMode === 'asset' ? 'Tile Asset Editor mode: visual placements only. Semantic layers are locked.' : 'Tilemap Builder mode: semantic/gameplay layer editing only.';
    setStatus(state.editMode === 'asset' ? 'Asset mode selected. Visual placements are edited in separate *.visual.json files.' : 'Semantic mode selected. Visual placements are locked.'); updateHud();
  }
  function setVisualTool(tool) { state.visualTool = tool; for (const [btn,t] of [[els.placeToolBtn,'place'],[els.selectToolBtn,'select'],[els.eraseToolBtn,'erase']]) btn.classList.toggle('active', tool===t); updateHud(); }
  function populateLayerSelect() { els.activeLayer.innerHTML=''; for (const l of SEMANTIC_LAYERS) { const o=document.createElement('option'); o.value=l; o.textContent=LAYER_LABELS[l]; els.activeLayer.appendChild(o); } }
  function renderPalette() { const items=PALETTES[state.activeLayer]||[]; els.palette.innerHTML=''; for (const item of items) { const b=document.createElement('button'); b.className=`tile-btn${state.selectedSemantic===item.id?' active':''}`; b.innerHTML=`<span class="swatch" style="background:${item.color}"></span><span>${item.label}</span>`; b.onclick=()=>{state.selectedSemantic=item.id; renderPalette(); updateHud();}; els.palette.appendChild(b); } }
  async function refreshMaps() { try { const r=await api('/api/maps'); state.maps=r.maps||[]; els.projectRootHint.textContent=`Project root: ${r.projectRoot}`; els.mapSelect.innerHTML=''; for (const m of state.maps) { const o=document.createElement('option'); o.value=m.fileName; const visual=m.hasVisualFile?` + ${m.visualPlacementCount} visual`:(m.hasLegacyAssetLayers?` + ${m.visualPlacementCount} legacy assetCells`:''); o.textContent=m.error?`${m.fileName} ERROR: ${m.error}`:`${m.displayName||m.mapId||m.fileName}${visual} (${m.fileName})`; els.mapSelect.appendChild(o); } if (!state.fileName && state.maps[0]) els.mapSelect.value=state.maps[0].fileName; setStatus(`Found ${state.maps.length} map file(s).`);} catch(e){setStatus(`Map scan failed: ${e.message}`);} }
  async function refreshAssets() { try { const r=await api('/api/assets'); state.assets=r.assets||[]; state.folders=r.folders||[]; els.assetFolderSelect.innerHTML='<option value="ALL">All folders</option>'; for (const f of state.folders) { const o=document.createElement('option'); o.value=f.folder; o.textContent=`${f.folder} (${f.count})`; els.assetFolderSelect.appendChild(o);} renderAssetOptions(); setStatus(`Found ${state.assets.length} image asset file(s).`);} catch(e){setStatus(`Asset scan failed: ${e.message}`);} }
  function renderAssetOptions() { const prev=els.assetSelect.value; const query=(els.assetSearch.value||'').toLowerCase(); const folder=els.assetFolderSelect.value||'ALL'; els.assetSelect.innerHTML=''; const filtered=state.assets.filter(a=>(folder==='ALL'||a.folder===folder)&&(!query||a.path.toLowerCase().includes(query))); for (const a of filtered) { const o=document.createElement('option'); o.value=a.path; o.textContent=`${a.path}${a.width?` (${a.width}×${a.height})`:''}`; o.dataset.tileSize=a.suggestedTileSize||32; els.assetSelect.appendChild(o); } if (filtered.length) { els.assetSelect.value=filtered.some(a=>a.path===prev)?prev:filtered[0].path; loadSelectedAsset(); } else { state.assetImage=null; drawAssetSheet(); updateCropPreview(); } }
  async function loadSelectedAsset() { const path=els.assetSelect.value; if (!path) return; state.assetImagePath=path; state.assetImageInfo=state.assets.find(a=>a.path===path)||null; const tile=state.assetImageInfo?.suggestedTileSize||32; els.gridSize.value=String([16,32,48,64].includes(tile)?tile:32); if (!state.crop.width || !state.crop.height) {state.crop.width=tile; state.crop.height=tile;} try { state.assetImage=await loadImage(path); syncCropInputsFromState(); drawAssetSheet(); updateCropPreview(); setStatus(`Loaded sprite sheet: ${path}`); } catch(e){ setStatus(`Could not load sprite sheet: ${e.message}`); } }
  async function loadSelectedMap() { const file=els.mapSelect.value; if (!file) return; if ((state.dirtySemantic||state.dirtyVisual) && !confirm('Unsaved changes. Load another map anyway?')) return; try { const r=await api(`/api/map?file=${encodeURIComponent(file)}`); state.fileName=r.fileName; state.visualFileName=r.visualFileName; state.map=normalizeMap(r.map); state.visual=normalizeVisual(r.visual); state.visualSource=r.visualSource; state.dirtySemantic=false; state.dirtyVisual=false; state.selectedPlacementId=null; state.undoStack=[]; state.redoStack=[]; updateMapForm(); centerMap(); setStatus(`Loaded ${r.fileName}. Visual source: ${r.visualSource}.`); } catch(e){ setStatus(`Load failed: ${e.message}`); } }
  function normalizeMap(map) { map.width=Number(map.width); map.height=Number(map.height); map.gameTileSizePx=Number(map.gameTileSizePx||32); map.layers=map.layers||{}; for (const l of SEMANTIC_LAYERS) if (!Array.isArray(map.layers[l])) map.layers[l]=emptyLayer(map.width,map.height); return map; }
  function normalizeVisual(visual) { if (!visual) visual={placements:[]}; if (!Array.isArray(visual.placements)) visual.placements=[]; visual.placements=visual.placements.map((p,i)=>({ id:p.id||uid(), label:p.label||'', assetPath:p.assetPath||'', crop:{x:Number(p.crop?.x??p.sx??0),y:Number(p.crop?.y??p.sy??0),width:Number(p.crop?.width??p.sw??32),height:Number(p.crop?.height??p.sh??32)}, tile:{x:Number(p.tile?.x??p.tileX??0),y:Number(p.tile?.y??p.tileY??0)}, draw:{widthTiles:Number(p.draw?.widthTiles??p.widthTiles??1),heightTiles:Number(p.draw?.heightTiles??p.heightTiles??1)}, anchor:p.anchor||'top-left', drawLayer:p.drawLayer||'objects', order:Number(p.order??i), notes:p.notes||'' })); return visual; }
  function updateMapForm() { if(!state.map)return; els.mapId.value=state.map.mapId||state.map.mapName||''; els.displayName.value=state.map.displayName||''; els.width.value=state.map.width; els.height.value=state.map.height; els.tileSize.value=state.map.gameTileSizePx; els.visualFileHint.textContent=`Visual file: ${state.visualFileName||'none'} (${state.visualSource||'unknown'}, ${state.visual?.placements?.length||0} placements)`; updateSelectedPlacementForm(); updateHud(); }
  function emptyLayer(w,h){return Array.from({length:h},()=>Array.from({length:w},()=>null));}
  function uid(){return `vp_${Math.random().toString(36).slice(2,10)}`;}
  function renderVisibility(){ els.layerVisibility.innerHTML=''; for(const l of SEMANTIC_LAYERS){const row=document.createElement('label'); row.className=`visibility-row${l===state.activeLayer?' active-layer':''}`; row.innerHTML=`<input type="checkbox" ${state.semanticVisibility[l]?'checked':''}/><span>${LAYER_LABELS[l]}</span>`; row.querySelector('input').onchange=(e)=>{state.semanticVisibility[l]=e.target.checked;}; els.layerVisibility.appendChild(row);} }
  function renderVisualVisibility(){ els.visualVisibility.innerHTML=''; for(const l of VISUAL_LAYERS){const row=document.createElement('label'); row.className=`visibility-row${l===els.drawLayer.value?' active-layer':''}`; row.innerHTML=`<input type="checkbox" ${state.visualVisibility[l]?'checked':''}/><span>${VISUAL_LAYER_LABELS[l]}</span>`; row.querySelector('input').onchange=(e)=>{state.visualVisibility[l]=e.target.checked;}; els.visualVisibility.appendChild(row);} }
  function showAllLayers(){ for(const l of SEMANTIC_LAYERS) state.semanticVisibility[l]=true; for(const l of VISUAL_LAYERS) state.visualVisibility[l]=true; renderVisibility(); renderVisualVisibility(); }
  function soloActiveLayer(){ if(state.editMode==='asset'){ for(const l of VISUAL_LAYERS) state.visualVisibility[l]=l===els.drawLayer.value; if(els.showSemanticOverlay.checked) state.semanticVisibility.markers=true; } else { for(const l of SEMANTIC_LAYERS) state.semanticVisibility[l]=l===state.activeLayer; } renderVisibility(); renderVisualVisibility(); }
  function resizeCanvas(){ const r=canvas.getBoundingClientRect(); const dpr=window.devicePixelRatio||1; canvas.width=Math.floor(r.width*dpr); canvas.height=Math.floor(r.height*dpr); ctx.setTransform(dpr,0,0,dpr,0,0); }
  function centerMap(){ const r=canvas.getBoundingClientRect(); const fit=Math.min((r.width*.84)/mapPixelW(),(r.height*.84)/mapPixelH()); state.zoom=clamp(fit,.05,16); state.panX=(r.width-mapPixelW()*state.zoom)/2; state.panY=(r.height-mapPixelH()*state.zoom)/2; updateHud(); }
  function mapPixelW(){return state.map?state.map.width*state.map.gameTileSizePx:1;} function mapPixelH(){return state.map?state.map.height*state.map.gameTileSizePx:1;}
  function eventToWorld(e){const r=canvas.getBoundingClientRect(); return {x:(e.clientX-r.left-state.panX)/state.zoom,y:(e.clientY-r.top-state.panY)/state.zoom};}
  function eventToTile(e){if(!state.map)return null; const w=eventToWorld(e); return {x:Math.floor(w.x/state.map.gameTileSizePx),y:Math.floor(w.y/state.map.gameTileSizePx)};}
  function pointerDown(e){ state.pointer.down=true; state.pointer.lastX=e.clientX; state.pointer.lastY=e.clientY; state.pointer.mode=(e.button===1||e.shiftKey)?'pan':(e.button===2?'erase':'paint'); state.pointer.dragStartTile=eventToTile(e); state.pointer.lastPlacedKey=null; if(state.editMode==='asset'&&state.visualTool==='select'&&state.pointer.mode==='paint'){ const p=findTopPlacementAtTile(state.pointer.dragStartTile); if(p){ selectPlacement(p.id); state.pointer.movedPlacementStart={x:p.tile.x,y:p.tile.y}; } } handlePointerAction(e); }
  function pointerMove(e){ const tile=eventToTile(e); state.hoverTile=tile; updateHoverHud(tile); if(!state.pointer.down)return; if(state.pointer.mode==='pan'){state.panX+=e.clientX-state.pointer.lastX; state.panY+=e.clientY-state.pointer.lastY; state.pointer.lastX=e.clientX; state.pointer.lastY=e.clientY; return;} if(state.editMode==='asset'&&state.visualTool==='select'&&state.pointer.movedPlacementStart&&tile){ const start=state.pointer.dragStartTile; const p=getSelectedPlacement(); if(start&&p){ p.tile.x=state.pointer.movedPlacementStart.x+(tile.x-start.x); p.tile.y=state.pointer.movedPlacementStart.y+(tile.y-start.y); state.dirtyVisual=true; updateSelectedPlacementForm(false); }} else handlePointerAction(e); }
  function pointerUp(){ state.pointer.down=false; state.pointer.mode=null; state.pointer.dragStartTile=null; state.pointer.movedPlacementStart=null; state.pointer.lastPlacedKey=null; updateHud(); }
  function handlePointerAction(e){ if(!state.map||state.pointer.mode==='pan')return; const tile=eventToTile(e); if(!tile||!inBounds(tile.x,tile.y))return; if(state.editMode==='asset') handleAssetAction(tile); else handleSemanticAction(tile, state.pointer.mode==='erase'?null:state.selectedSemantic); }
  function handleSemanticAction(tile,value){ const size=Number(els.brushSize.value||1), off=Math.floor(size/2); for(let y=tile.y-off;y<tile.y-off+size;y++)for(let x=tile.x-off;x<tile.x-off+size;x++)if(inBounds(x,y))state.map.layers[state.activeLayer][y][x]=value; state.dirtySemantic=true; }
  function handleAssetAction(tile){ if(state.pointer.mode==='erase'||state.visualTool==='erase'){ const p=findTopPlacementAtTile(tile); if(p){ pushUndo(); state.visual.placements=state.visual.placements.filter(q=>q.id!==p.id); state.selectedPlacementId=null; state.dirtyVisual=true; updateSelectedPlacementForm(); } return; } if(state.visualTool==='select'){ const p=findTopPlacementAtTile(tile); if(p) selectPlacement(p.id); return; } if(state.visualTool==='place'){ const key=`${tile.x},${tile.y}`; if(state.pointer.lastPlacedKey===key&&!els.stampLine.checked)return; state.pointer.lastPlacedKey=key; placeCurrentCrop(tile.x,tile.y); } }
  function placeCurrentCrop(x,y){ if(!state.assetImagePath){setStatus('Choose a sprite sheet first.');return;} pushUndo(); const p={ id:uid(), label:els.placementLabel.value||'', assetPath:state.assetImagePath, crop:{...state.crop}, tile:{x,y}, draw:{widthTiles:Number(els.drawWTiles.value||1),heightTiles:Number(els.drawHTiles.value||1)}, anchor:els.anchor.value, drawLayer:els.drawLayer.value, order:nextOrder(), notes:''}; state.visual.placements.push(p); selectPlacement(p.id); state.dirtyVisual=true; }
  function nextOrder(){return Math.max(0,...(state.visual?.placements||[]).map(p=>Number(p.order)||0))+1;}
  function onWheel(e){ e.preventDefault(); const r=canvas.getBoundingClientRect(); const mx=e.clientX-r.left,my=e.clientY-r.top; const before={x:(mx-state.panX)/state.zoom,y:(my-state.panY)/state.zoom}; state.zoom=clamp(state.zoom*(e.deltaY<0?1.1:.9),.05,24); state.panX=mx-before.x*state.zoom; state.panY=my-before.y*state.zoom; updateHud(); }
  function draw(){ const r=canvas.getBoundingClientRect(); ctx.clearRect(0,0,r.width,r.height); ctx.fillStyle='#05070d'; ctx.fillRect(0,0,r.width,r.height); if(state.map){ctx.save(); ctx.translate(state.panX,state.panY); ctx.scale(state.zoom,state.zoom); ctx.imageSmoothingEnabled=false; ctx.fillStyle='#111827'; ctx.fillRect(0,0,mapPixelW(),mapPixelH()); if(state.viewMode==='semantic') drawSemanticLayers({alpha:1,markers:true}); else if(state.viewMode==='asset'){ drawVisualPlacements(); if(els.showSemanticOverlay.checked) drawSemanticLayers({alpha:Number(els.semanticOverlayAlpha.value||.35),markers:els.showMarkerGlyphs.checked,overlay:true}); } else { drawSemanticLayers({alpha:Number(els.semanticOverlayAlpha.value||.35),markers:false,overlay:true}); drawVisualPlacements(); if(els.showMarkerGlyphs.checked) drawMarkerOverlay(); } if(els.showGrid.checked) drawGrid(); drawSelectionOutline(); ctx.strokeStyle='#fff'; ctx.lineWidth=2/state.zoom; ctx.strokeRect(0,0,mapPixelW(),mapPixelH()); ctx.restore();} else {ctx.fillStyle='#9db2c8'; ctx.font='20px Segoe UI,Arial'; ctx.fillText('Load a map to begin.',36,52);} updateHud(); requestAnimationFrame(draw); }
  function drawSemanticLayers(opts={}){ const tile=state.map.gameTileSizePx; for(const layer of SEMANTIC_LAYERS){ if(!state.semanticVisibility[layer])continue; if(layer==='markers'&&!opts.markers)continue; const rows=state.map.layers[layer]||[]; const base=layer==='ground'?.75:layer==='structures'?.85:layer==='objects'?.88:.85; for(let y=0;y<state.map.height;y++)for(let x=0;x<state.map.width;x++){ const id=rows[y]?.[x]; if(!id)continue; ctx.save(); ctx.globalAlpha=(opts.alpha??1)*base; ctx.fillStyle=colorById[id]||'#ff00ff'; ctx.fillRect(x*tile,y*tile,tile,tile); ctx.restore(); if(layer==='markers'&&els.showMarkerGlyphs.checked) drawMarkerGlyph(id,x,y,tile); } } }
  function drawVisualPlacements(){ const tile=state.map.gameTileSizePx; const placements=[...(state.visual?.placements||[])].filter(p=>state.visualVisibility[p.drawLayer]!==false).sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)); for(const p of placements){ const img=getCachedImage(p.assetPath); const rect=placementRect(p,tile); if(img?.complete&&img.naturalWidth){ ctx.drawImage(img,p.crop.x,p.crop.y,p.crop.width,p.crop.height,rect.x,rect.y,rect.w,rect.h); } else { ctx.fillStyle='#00eaff'; ctx.fillRect(rect.x,rect.y,rect.w,rect.h); } } }
  function placementRect(p,tile){ const w=p.draw.widthTiles*tile,h=p.draw.heightTiles*tile; let x=p.tile.x*tile,y=p.tile.y*tile; if(p.anchor==='center'){x-=w/2-tile/2;y-=h/2-tile/2;} else if(p.anchor==='bottom-center'){x-=w/2-tile/2;y-=h-tile;} return {x,y,w,h}; }
  function drawSelectionOutline(){ const p=getSelectedPlacement(); if(!p||state.editMode!=='asset')return; const r=placementRect(p,state.map.gameTileSizePx); ctx.save(); ctx.strokeStyle='#fff200'; ctx.lineWidth=3/state.zoom; ctx.strokeRect(r.x,r.y,r.w,r.h); ctx.fillStyle='rgba(255,242,0,.12)'; ctx.fillRect(r.x,r.y,r.w,r.h); ctx.restore(); }
  function drawMarkerOverlay(){ const old={...state.semanticVisibility}; for(const l of SEMANTIC_LAYERS)state.semanticVisibility[l]=l==='markers'; drawSemanticLayers({alpha:1,markers:true}); state.semanticVisibility=old; }
  function drawMarkerGlyph(id,x,y,tile){ const cx=x*tile+tile/2,cy=y*tile+tile/2; ctx.save(); ctx.globalAlpha=1; ctx.fillStyle='#06111f'; ctx.strokeStyle='#fff'; ctx.lineWidth=1.4/state.zoom; ctx.beginPath(); ctx.arc(cx,cy,tile*.24,0,Math.PI*2); ctx.fill(); ctx.stroke(); ctx.fillStyle='#fff'; ctx.font=`${Math.max(8,tile*.22)}px Segoe UI`; ctx.textAlign='center'; ctx.textBaseline='middle'; ctx.fillText(String(id).split('_').map(s=>s[0]).join('').slice(0,3).toUpperCase(),cx,cy); ctx.restore(); }
  function drawGrid(){ const tile=state.map.gameTileSizePx; ctx.save(); ctx.strokeStyle='rgba(255,255,255,.28)'; ctx.lineWidth=1/state.zoom; for(let x=0;x<=state.map.width;x++){ctx.beginPath();ctx.moveTo(x*tile,0);ctx.lineTo(x*tile,mapPixelH());ctx.stroke();} for(let y=0;y<=state.map.height;y++){ctx.beginPath();ctx.moveTo(0,y*tile);ctx.lineTo(mapPixelW(),y*tile);ctx.stroke();} ctx.restore(); }
  function sheetPointerDown(e){ state.sheetPointer.down=true; state.sheetPointer.lastX=e.clientX; state.sheetPointer.lastY=e.clientY; state.sheetPointer.mode=(e.button===1||e.button===2||e.shiftKey)?'pan':'select'; if(state.sheetPointer.mode==='select') selectCropFromSheet(e); }
  function sheetPointerMove(e){ if(!state.sheetPointer.down||state.sheetPointer.mode!=='pan')return; state.sheetPan.x+=e.clientX-state.sheetPointer.lastX; state.sheetPan.y+=e.clientY-state.sheetPointer.lastY; state.sheetPointer.lastX=e.clientX; state.sheetPointer.lastY=e.clientY; els.sheetPanX.value=Math.round(state.sheetPan.x); els.sheetPanY.value=Math.round(state.sheetPan.y); drawAssetSheet(); }
  function sheetPointerUp(){ state.sheetPointer.down=false; }
  function onSheetWheel(e){ e.preventDefault(); els.sheetZoom.value=clamp(Number(els.sheetZoom.value||2)*(e.deltaY<0?1.15:.85),.25,8).toFixed(2); drawAssetSheet(); }
  function drawAssetSheet(){ const r=assetCanvas.getBoundingClientRect(); const dpr=window.devicePixelRatio||1; assetCanvas.width=Math.floor(r.width*dpr); assetCanvas.height=Math.floor(r.height*dpr); assetCtx.setTransform(dpr,0,0,dpr,0,0); assetCtx.clearRect(0,0,r.width,r.height); assetCtx.fillStyle='#08111d'; assetCtx.fillRect(0,0,r.width,r.height); if(!state.assetImage){ assetCtx.fillStyle='#9db2c8'; assetCtx.fillText('No asset sheet loaded.',12,24); return; } const scale=Number(els.sheetZoom.value||2); state.sheetPan.x=Number(els.sheetPanX.value||0); state.sheetPan.y=Number(els.sheetPanY.value||0); assetCtx.imageSmoothingEnabled=false; assetCtx.drawImage(state.assetImage,state.sheetPan.x,state.sheetPan.y,state.assetImage.width*scale,state.assetImage.height*scale); if(els.snapToGrid.checked){ const g=Number(els.gridSize.value||32); assetCtx.strokeStyle='rgba(255,255,255,.24)'; assetCtx.lineWidth=1; for(let x=0;x<=state.assetImage.width;x+=g){const px=state.sheetPan.x+x*scale; assetCtx.beginPath(); assetCtx.moveTo(px,state.sheetPan.y); assetCtx.lineTo(px,state.sheetPan.y+state.assetImage.height*scale); assetCtx.stroke();} for(let y=0;y<=state.assetImage.height;y+=g){const py=state.sheetPan.y+y*scale; assetCtx.beginPath(); assetCtx.moveTo(state.sheetPan.x,py); assetCtx.lineTo(state.sheetPan.x+state.assetImage.width*scale,py); assetCtx.stroke();}}
    assetCtx.strokeStyle='#fff200'; assetCtx.lineWidth=3; assetCtx.strokeRect(state.sheetPan.x+state.crop.x*scale,state.sheetPan.y+state.crop.y*scale,state.crop.width*scale,state.crop.height*scale); }
  function selectCropFromSheet(e){ if(!state.assetImage)return; const r=assetCanvas.getBoundingClientRect(), scale=Number(els.sheetZoom.value||2); let x=(e.clientX-r.left-state.sheetPan.x)/scale, y=(e.clientY-r.top-state.sheetPan.y)/scale; if(x<0||y<0||x>=state.assetImage.width||y>=state.assetImage.height)return; if(els.snapToGrid.checked){ const g=Number(els.gridSize.value||32); x=Math.floor(x/g)*g; y=Math.floor(y/g)*g; state.crop.width=Number(els.cropW.value||g); state.crop.height=Number(els.cropH.value||g); } state.crop.x=Math.round(x); state.crop.y=Math.round(y); syncCropInputsFromState(); updateCropPreview(); drawAssetSheet(); }
  function syncCropFromInputs(){ state.crop={x:Math.max(0,Number(els.cropX.value||0)),y:Math.max(0,Number(els.cropY.value||0)),width:Math.max(1,Number(els.cropW.value||32)),height:Math.max(1,Number(els.cropH.value||32))}; if(els.snapToGrid.checked){ const g=Number(els.gridSize.value||32); state.crop.x=Math.floor(state.crop.x/g)*g; state.crop.y=Math.floor(state.crop.y/g)*g; } syncCropInputsFromState(); updateCropPreview(); drawAssetSheet(); }
  function syncCropInputsFromState(){ els.cropX.value=state.crop.x; els.cropY.value=state.crop.y; els.cropW.value=state.crop.width; els.cropH.value=state.crop.height; }
  function updateCropPreview(){ cropCtx.clearRect(0,0,cropPreview.width,cropPreview.height); cropCtx.fillStyle='#08111d'; cropCtx.fillRect(0,0,cropPreview.width,cropPreview.height); if(state.assetImage){ cropCtx.imageSmoothingEnabled=false; cropCtx.drawImage(state.assetImage,state.crop.x,state.crop.y,state.crop.width,state.crop.height,0,0,cropPreview.width,cropPreview.height); } els.cropInfo.textContent=state.assetImagePath?`Sheet: ${state.assetImagePath}\nCrop: x${state.crop.x} y${state.crop.y} ${state.crop.width}×${state.crop.height}\nTest footprint: ${els.drawWTiles.value}×${els.drawHTiles.value} tile(s)`: 'No crop selected.'; }
  function selectPlacement(id){ state.selectedPlacementId=id; const p=getSelectedPlacement(); if(p){ state.crop={...p.crop}; if(p.assetPath&&p.assetPath!==state.assetImagePath){ const found=state.assets.find(a=>a.path===p.assetPath); if(found){ els.assetFolderSelect.value=found.folder; renderAssetOptions(); els.assetSelect.value=found.path; loadSelectedAsset(); } } } updateSelectedPlacementForm(); updateCropPreview(); updateHud(); }
  function getSelectedPlacement(){return state.visual?.placements?.find(p=>p.id===state.selectedPlacementId)||null;}
  function updateSelectedPlacementForm(syncCrop=true){ const p=getSelectedPlacement(); if(!p){ els.selectedPlacementInfo.textContent='No placement selected.'; return; } if(syncCrop){ els.drawLayer.value=p.drawLayer; els.drawWTiles.value=p.draw.widthTiles; els.drawHTiles.value=p.draw.heightTiles; els.anchor.value=p.anchor; els.drawOrder.value=p.order; els.placementLabel.value=p.label||''; } els.selectedPlacementInfo.textContent=`Selected placement\nID: ${p.id}\nLabel: ${p.label||'(none)'}\nAsset: ${p.assetPath}\nCrop: ${p.crop.x},${p.crop.y},${p.crop.width},${p.crop.height}\nTile: ${p.tile.x},${p.tile.y}\nDraw: ${p.draw.widthTiles}×${p.draw.heightTiles} tiles\nLayer/order: ${p.drawLayer} / ${p.order}`; renderVisualVisibility(); }
  function syncSelectedPlacementFromForm(){ const p=getSelectedPlacement(); updateCropPreview(); if(!p)return; pushUndo(); p.drawLayer=els.drawLayer.value; p.draw.widthTiles=Number(els.drawWTiles.value||1); p.draw.heightTiles=Number(els.drawHTiles.value||1); p.anchor=els.anchor.value; p.order=Number(els.drawOrder.value||0); p.label=els.placementLabel.value||''; state.dirtyVisual=true; updateSelectedPlacementForm(false); }
  function duplicateSelected(){ const p=getSelectedPlacement(); if(!p)return; pushUndo(); const q=JSON.parse(JSON.stringify(p)); q.id=uid(); q.tile.x+=1; q.tile.y+=1; q.order=nextOrder(); state.visual.placements.push(q); selectPlacement(q.id); state.dirtyVisual=true; }
  function deleteSelected(){ const p=getSelectedPlacement(); if(!p)return; pushUndo(); state.visual.placements=state.visual.placements.filter(q=>q.id!==p.id); state.selectedPlacementId=null; state.dirtyVisual=true; updateSelectedPlacementForm(); }
  function copySelected(){ const p=getSelectedPlacement(); if(p){ state.copiedPlacement=JSON.parse(JSON.stringify(p)); setStatus('Copied selected visual placement.'); } }
  function pasteCopied(){ if(!state.copiedPlacement||!state.visual)return; pushUndo(); const q=JSON.parse(JSON.stringify(state.copiedPlacement)); q.id=uid(); q.tile.x+=1; q.tile.y+=1; q.order=nextOrder(); state.visual.placements.push(q); selectPlacement(q.id); state.dirtyVisual=true; }
  function bumpOrder(delta){ const p=getSelectedPlacement(); if(!p)return; pushUndo(); p.order=delta>0?nextOrder():Math.min(0,...state.visual.placements.map(q=>Number(q.order)||0))-1; state.dirtyVisual=true; updateSelectedPlacementForm(); }
  function pushUndo(){ if(!state.visual)return; state.undoStack.push(JSON.stringify(state.visual.placements)); if(state.undoStack.length>50)state.undoStack.shift(); state.redoStack=[]; }
  function undo(){ if(!state.undoStack.length||!state.visual)return; state.redoStack.push(JSON.stringify(state.visual.placements)); state.visual.placements=JSON.parse(state.undoStack.pop()); state.selectedPlacementId=null; state.dirtyVisual=true; updateSelectedPlacementForm(); }
  function redo(){ if(!state.redoStack.length||!state.visual)return; state.undoStack.push(JSON.stringify(state.visual.placements)); state.visual.placements=JSON.parse(state.redoStack.pop()); state.selectedPlacementId=null; state.dirtyVisual=true; updateSelectedPlacementForm(); }
  function findTopPlacementAtTile(tile){ if(!tile||!state.visual)return null; const t=state.map.gameTileSizePx; const px=tile.x*t+t/2, py=tile.y*t+t/2; return [...state.visual.placements].filter(p=>state.visualVisibility[p.drawLayer]!==false).sort((a,b)=>(Number(b.order)||0)-(Number(a.order)||0)).find(p=>{const r=placementRect(p,t); return px>=r.x&&py>=r.y&&px<=r.x+r.w&&py<=r.y+r.h;})||null; }
  async function saveSemantic(){ if(!state.map||!state.fileName)return; if(!confirm('Save semantic map JSON? A backup will be created first.'))return; try{ state.map.mapId=safeMapId(els.mapId.value||state.map.mapId); state.map.mapName=state.map.mapId; state.map.displayName=els.displayName.value||state.map.mapId; const r=await api('/api/map/save-semantic',{method:'POST',body:JSON.stringify({fileName:state.fileName,map:state.map})}); state.dirtySemantic=false; setStatus(`Semantic save complete.\nBackup: ${r.backupFile||'(new file)'}\nReport: ${r.reportFile}`); await refreshMaps(); }catch(e){setStatus(`Semantic save failed: ${e.message}`);} }
  async function validateVisual(){ if(!state.visual||!state.fileName)return; try{ const r=await api('/api/visual/validate',{method:'POST',body:JSON.stringify({fileName:state.fileName,visual:prepareVisualForSave()})}); setStatus(`Visual validation OK.\nPlacements: ${r.placementCount}\nAssets used: ${r.assetSheetsUsed.length}\nWarnings: ${(r.warnings||[]).join('\n')||'none'}`); }catch(e){setStatus(`Visual validation failed:\n${e.message}`);} }
  async function saveVisual(){ if(!state.visual||!state.fileName)return; if(!confirm(`Save visual placements to ${state.visualFileName}? A backup will be created before overwrite.`))return; try{ const r=await api('/api/visual/save',{method:'POST',body:JSON.stringify({fileName:state.fileName,visual:prepareVisualForSave()})}); state.dirtyVisual=false; state.visualFileName=r.visualFileName; els.visualFileHint.textContent=`Visual file: ${r.visualFileName} (${state.visual.placements.length} placements)`; setStatus(`Visual save complete.\nChanged: ${r.report.filesChanged.join(', ')}\nBackup: ${r.backupFile||'(created new visual file)'}\nReport: ${r.reportFile}\nWarnings: ${(r.report.validation.warnings||[]).join('\n')||'none'}`); await refreshMaps(); }catch(e){setStatus(`Visual save failed:\n${e.message}`);} }
  function prepareVisualForSave(){ const visual=JSON.parse(JSON.stringify(state.visual)); visual.format='lulus_visual_placements_v1'; visual.version='1.0'; visual.mapFile=state.fileName; visual.mapId=safeMapId(els.mapId.value||state.map.mapId||'map'); visual.displayName=`${els.displayName.value||visual.mapId} Visuals`; visual.width=state.map.width; visual.height=state.map.height; visual.gameTileSizePx=state.map.gameTileSizePx; visual.visualLayerOrder=VISUAL_LAYERS; visual.placements=visual.placements.map((p,i)=>({...p, order:Number.isFinite(Number(p.order))?Number(p.order):i})); return visual; }
  function downloadVisual(){ if(!state.visual)return; const visual=prepareVisualForSave(); const blob=new Blob([JSON.stringify(visual,null,2)+'\n'],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=state.visualFileName||`${visual.mapId}.visual.json`; document.body.appendChild(a); a.click(); URL.revokeObjectURL(a.href); a.remove(); setStatus('Downloaded visual JSON copy. Project file was not changed.'); }
  function clearSemanticLayer(){ if(!state.map)return; if(!confirm(`Clear semantic ${LAYER_LABELS[state.activeLayer]} layer?`))return; state.map.layers[state.activeLayer]=emptyLayer(state.map.width,state.map.height); state.dirtySemantic=true; }
  function onKeyDown(e){ if(state.editMode!=='asset')return; if(e.key==='Delete'||e.key==='Backspace')deleteSelected(); if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'){e.preventDefault(); copySelected();} if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'){e.preventDefault(); pasteCopied();} if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault(); undo();} if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault(); redo();} }
  function updateHoverHud(tile){ if(!tile||!state.map||!inBounds(tile.x,tile.y)){els.tileHud.textContent='Tile: out'; els.hoverHud.textContent='Hover: none'; return;} els.tileHud.textContent=`Tile: ${tile.x}, ${tile.y}`; const parts=[]; for(const l of SEMANTIC_LAYERS){const v=state.map.layers[l]?.[tile.y]?.[tile.x]; if(v)parts.push(`${l}:${v}`);} const p=findTopPlacementAtTile(tile); if(p)parts.push(`visual:${p.label||p.id}`); els.hoverHud.textContent=parts.length?`Hover: ${parts.join(' | ')}`:'Hover: empty'; }
  function updateHud(){ els.fileHud.textContent=`${state.fileName||'No map loaded'}${state.dirtySemantic?' *semantic*':''}${state.dirtyVisual?' *visual*':''}`; els.modeHud.textContent=`Mode: ${state.editMode==='asset'?'Tile Asset Editor':'Tilemap Builder'} / ${viewLabel(state.viewMode)} / tool ${state.visualTool}`; const p=getSelectedPlacement(); els.selectedHud.textContent=state.editMode==='asset' ? (p?`Selected: ${p.label||p.id} / ${p.drawLayer} / ${p.draw.widthTiles}×${p.draw.heightTiles}`:`Selected crop: ${state.assetImagePath?state.assetImagePath.split('/').pop():'none'} ${state.crop.x},${state.crop.y},${state.crop.width}×${state.crop.height}`) : `Selected: ${state.selectedSemantic||'eraser'} / ${LAYER_LABELS[state.activeLayer]}`; els.zoomHud.textContent=`Zoom: ${Math.round(state.zoom*100)}%`; }
  function viewLabel(v){return v==='asset'?'Actual Asset View':v==='combined'?'Combined View':'Color Coding View';}
  function setStatus(msg){ els.statusLine.textContent=msg; }
  function inBounds(x,y){return state.map&&x>=0&&y>=0&&x<state.map.width&&y<state.map.height;}
  function safeMapId(raw){return String(raw||'map').trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'')||'map';}
  function clamp(v,min,max){return Math.max(min,Math.min(max,Number(v)||0));}
  function getCachedImage(path){ if(!path)return null; if(state.imageCache.has(path))return state.imageCache.get(path); const img=new Image(); img.onload=()=>{}; img.onerror=()=>setStatus(`Could not preview asset: ${path}`); img.src=`/api/project-asset?path=${encodeURIComponent(path)}`; state.imageCache.set(path,img); return img; }
  function loadImage(path){ return new Promise((resolve,reject)=>{ const img=new Image(); img.onload=()=>{state.imageCache.set(path,img); resolve(img);}; img.onerror=()=>reject(new Error(path)); img.src=`/api/project-asset?path=${encodeURIComponent(path)}`; }); }
  init();
})();
